name: Deploy

on: push

jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
    - name: Deploy Stage
      uses: fjogeleit/http-request-action@master
      with:
        url: 'https://api.render.com/deploy/srv-c4il0f76d9kh5recu2hg?key=N3dZsH0e58Q'
        method: 'GET'
